const COURSES = [
  {
    "name": "Albert Park Golf Course",
    "suburb": "Melbourne",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Public",
    "notes": "Parkland on Albert Park Lake; club hire available; city views",
    "lat": -37.8136,
    "lng": 144.9631
  },
  {
    "name": "Yarra Bend Golf",
    "suburb": "Fairfield",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Public",
    "notes": "4 km from CBD; best inner-city public course in Australia; driving range",
    "lat": -37.7833,
    "lng": 145.0167
  },
  {
    "name": "Burnley Golf Course",
    "suburb": "Burnley",
    "holes": 9,
    "par": "32",
    "fee9": "$18\u2013$25",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Short public 9-hole near Richmond/CBD",
    "lat": -37.8333,
    "lng": 145.0
  },
  {
    "name": "Ivanhoe Public Golf Course",
    "suburb": "Ivanhoe",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Public",
    "notes": "Popular 18-hole suburban public course",
    "lat": -37.7667,
    "lng": 145.0333
  },
  {
    "name": "Brighton Public Golf Course",
    "suburb": "Brighton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$50",
    "access": "Public",
    "notes": "Open 7 days; driving range on site",
    "lat": -37.9167,
    "lng": 144.9833
  },
  {
    "name": "Bundoora Park Public Golf Course",
    "suburb": "Bundoora",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Public",
    "notes": "Bush parkland; no membership required",
    "lat": -37.7,
    "lng": 145.0667
  },
  {
    "name": "Keilor Public Golf Course",
    "suburb": "Keilor North",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Public",
    "notes": "North-west metro public course",
    "lat": -37.7167,
    "lng": 144.8333
  },
  {
    "name": "Sandringham Golf Links (Sandy Golf Links)",
    "suburb": "Cheltenham",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$85",
    "access": "Public",
    "notes": "Council-owned Sandbelt course; public access daily",
    "lat": -37.95,
    "lng": 145.05
  },
  {
    "name": "City of Kingston Public Golf Course",
    "suburb": "Cheltenham",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$45",
    "access": "Public",
    "notes": "Council-run; open to all",
    "lat": -37.95,
    "lng": 145.05
  },
  {
    "name": "Malvern Valley Public Golf Club",
    "suburb": "Malvern East",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$30\u2013$48",
    "access": "Public",
    "notes": "Well-maintained inner suburban course",
    "lat": -37.8667,
    "lng": 145.05
  },
  {
    "name": "Morack Public Golf Course",
    "suburb": "Vermont South",
    "holes": 18,
    "par": "70",
    "fee9": "$18\u2013$24",
    "fee18": "$28\u2013$40",
    "access": "Public",
    "notes": "Popular eastern-suburbs public course; covered driving range; par 70",
    "lat": -37.8833,
    "lng": 145.2167
  },
  {
    "name": "Elsternwick Park Golf Club",
    "suburb": "Elsternwick",
    "holes": 9,
    "par": "29",
    "fee9": "$18\u2013$25",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Par-3 9-hole public course",
    "lat": -37.8833,
    "lng": 145.0
  },
  {
    "name": "Heathmont Par 3 Golf Course",
    "suburb": "Heathmont",
    "holes": 9,
    "par": "27",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Beginner-friendly par-3 public course",
    "lat": -37.8167,
    "lng": 145.2333
  },
  {
    "name": "Eynesbury Golf",
    "suburb": "Eynesbury",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$45\u2013$70",
    "access": "Public",
    "notes": "Tom Watson design; pay-and-play resort community",
    "lat": -37.7333,
    "lng": 144.5167
  },
  {
    "name": "Growling Frog Golf Course",
    "suburb": "Yan Yean",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$40\u2013$65",
    "access": "Public",
    "notes": "High-quality public course north of Melbourne",
    "lat": -37.5667,
    "lng": 145.15
  },
  {
    "name": "Craigieburn Public Golf Course",
    "suburb": "Craigieburn",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Public",
    "notes": "Public in Melbourne's north growth corridor",
    "lat": -37.5833,
    "lng": 144.9333
  },
  {
    "name": "Royal Park Golf Course",
    "suburb": "Parkville",
    "holes": 9,
    "par": "30",
    "fee9": "$16\u2013$22",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Adjacent to Melbourne Zoo; public 9-hole",
    "lat": -37.7833,
    "lng": 144.95
  },
  {
    "name": "Riverside Golf & Recreation Centre (Ascot Vale)",
    "suburb": "Ascot Vale",
    "holes": 9,
    "par": "32",
    "fee9": "$16\u2013$22",
    "fee18": "N/A",
    "access": "Public",
    "notes": "9-hole public along Maribyrnong River",
    "lat": -37.7833,
    "lng": 144.9167
  },
  {
    "name": "Yarrambat Park Golf Course",
    "suburb": "Yarrambat",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Public",
    "notes": "Northern suburbs public parkland course",
    "lat": -37.65,
    "lng": 145.1333
  },
  {
    "name": "Plenty Views Golf Park",
    "suburb": "Plenty",
    "holes": 9,
    "par": "30",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Short 9-hole public; driving range",
    "lat": -37.6833,
    "lng": 145.1333
  },
  {
    "name": "Rowville Lakes Golf Club",
    "suburb": "Rowville",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Public",
    "notes": "Parkland with water features; public access",
    "lat": -37.9333,
    "lng": 145.2167
  },
  {
    "name": "Churchill Park Golf Club",
    "suburb": "Endeavour Hills",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Public",
    "notes": "South-east suburban public course",
    "lat": -37.95,
    "lng": 145.2667
  },
  {
    "name": "Bacchus Marsh West Golf Club",
    "suburb": "Bacchus Marsh",
    "holes": 9,
    "par": "34",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Small 9-hole public",
    "lat": -37.6667,
    "lng": 144.4333
  },
  {
    "name": "Australian Pitch & Putt Waverley",
    "suburb": "Mulgrave",
    "holes": 18,
    "par": "54",
    "fee9": "$14\u2013$22",
    "fee18": "$22\u2013$30",
    "access": "Public",
    "notes": "Par-3 pitch & putt; popular family course",
    "lat": -37.9333,
    "lng": 145.1833
  },
  {
    "name": "Club Mandalay",
    "suburb": "Beveridge",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Public",
    "notes": "Growth corridor public course",
    "lat": -37.4667,
    "lng": 144.9833
  },
  {
    "name": "Gardiners Run Golf & Country Club",
    "suburb": "Lilydale",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Public",
    "notes": "Public Yarra Valley course",
    "lat": -37.75,
    "lng": 145.35
  },
  {
    "name": "Altona Lakes Golf Club",
    "suburb": "Altona North",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Semi-Private",
    "notes": "Members' club; public tee times available",
    "lat": -37.85,
    "lng": 144.85
  },
  {
    "name": "Bacchus Marsh Golf Club",
    "suburb": "Bacchus Marsh",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Semi-Private",
    "notes": "Western Melbourne; semi-private",
    "lat": -37.6667,
    "lng": 144.4333
  },
  {
    "name": "Ballan Golf Club",
    "suburb": "Ballan",
    "holes": 9,
    "par": "35",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small town 9-hole semi-private",
    "lat": -37.6,
    "lng": 144.2333
  },
  {
    "name": "Camberwell Golf Club",
    "suburb": "Balwyn North",
    "holes": 9,
    "par": "30",
    "fee9": "$18\u2013$24",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole; members' club; visitors welcome",
    "lat": -37.7833,
    "lng": 145.0833
  },
  {
    "name": "Cheltenham Golf Club",
    "suburb": "Cheltenham",
    "holes": 9,
    "par": "30",
    "fee9": "$18\u2013$24",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole Sandbelt-adjacent; visitors welcome",
    "lat": -37.95,
    "lng": 145.05
  },
  {
    "name": "Chirnside Park Country Club",
    "suburb": "Chirnside Park",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Semi-Private",
    "notes": "Yarra Valley fringe; open visitor tee times",
    "lat": -37.75,
    "lng": 145.3333
  },
  {
    "name": "Cranbourne Golf Club",
    "suburb": "Cranbourne North",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$48",
    "access": "Semi-Private",
    "notes": "South-east growth corridor; semi-private",
    "lat": -38.0833,
    "lng": 145.2833
  },
  {
    "name": "Creekside Golf Club",
    "suburb": "Vermont South",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$48",
    "access": "Semi-Private",
    "notes": "South-east suburbs; visitors welcome",
    "lat": -37.8833,
    "lng": 145.2167
  },
  {
    "name": "Dorset Golf Course",
    "suburb": "Croydon",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "Yarra Valley fringe; semi-private",
    "lat": -37.7833,
    "lng": 145.2833
  },
  {
    "name": "Eastwood Golf Club",
    "suburb": "Kilsyth",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "Eastern suburbs; visitors welcome",
    "lat": -37.8,
    "lng": 145.3
  },
  {
    "name": "Forest Hills Golf Club",
    "suburb": "Dingley Village",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Semi-Private",
    "notes": "Semi-private south-east Melbourne",
    "lat": -37.9833,
    "lng": 145.1167
  },
  {
    "name": "Freeway Golf",
    "suburb": "Balwyn North",
    "holes": 9,
    "par": "30",
    "fee9": "$18\u2013$24",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole par-3; semi-private",
    "lat": -37.7833,
    "lng": 145.0833
  },
  {
    "name": "Glen Waverley Golf Club",
    "suburb": "Wheelers Hill",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "South-east Melbourne; visitor tee times",
    "lat": -37.9,
    "lng": 145.2
  },
  {
    "name": "Goonawarra Golf Club",
    "suburb": "Sunbury",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Semi-Private",
    "notes": "Sunbury; semi-private; visitors welcome",
    "lat": -37.5833,
    "lng": 144.7167
  },
  {
    "name": "Kings Park Golf Club",
    "suburb": "Bundoora",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "Semi-private northern suburbs",
    "lat": -37.7,
    "lng": 145.0667
  },
  {
    "name": "Kooringal Golf Club",
    "suburb": "Altona",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "Western suburbs; semi-private",
    "lat": -37.8667,
    "lng": 144.8333
  },
  {
    "name": "Latrobe Golf Club",
    "suburb": "Alphington",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Semi-Private",
    "notes": "Inner north; semi-private; visitors welcome",
    "lat": -37.7833,
    "lng": 145.0333
  },
  {
    "name": "Melton Valley Golf Club",
    "suburb": "Melton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$48",
    "access": "Semi-Private",
    "notes": "Well-reviewed; semi-private west Melbourne",
    "lat": -37.6833,
    "lng": 144.5833
  },
  {
    "name": "Patterson River Golf Club",
    "suburb": "Bonbeach",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Semi-Private",
    "notes": "South-east; semi-private/resort",
    "lat": -38.1167,
    "lng": 145.1167
  },
  {
    "name": "RAAF Williams Golf Club",
    "suburb": "Laverton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "Defence base course; semi-private",
    "lat": -37.8667,
    "lng": 144.7667
  },
  {
    "name": "Rossdale Golf Club",
    "suburb": "Aspendale",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Semi-Private",
    "notes": "'Melbourne's Friendliest Golf Club'; bayside banksias & pines; visitors welcome",
    "lat": -38.0333,
    "lng": 145.1
  },
  {
    "name": "Scotchmans Creek Golf Club",
    "suburb": "Scoresby",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Semi-Private",
    "notes": "South-east semi-private; visitors welcome",
    "lat": -37.9,
    "lng": 145.2333
  },
  {
    "name": "Settlers Run Golf & Country Club",
    "suburb": "Botanic Ridge",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$69\u2013$89",
    "access": "Semi-Private",
    "notes": "Greg Norman design; Top-100 ranked; public access Mon/Wed/Fri",
    "lat": -38.15,
    "lng": 145.2167
  },
  {
    "name": "South Pines Golf Club",
    "suburb": "South Morang",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Semi-Private",
    "notes": "Northern suburbs; semi-private; visitors welcome",
    "lat": -37.65,
    "lng": 145.1
  },
  {
    "name": "Strathallan Golf Club",
    "suburb": "Bundoora",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Semi-Private",
    "notes": "Highly reviewed semi-private; northern suburbs",
    "lat": -37.7,
    "lng": 145.0667
  },
  {
    "name": "Werribee Park Golf Club",
    "suburb": "Werribee",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Semi-Private",
    "notes": "Near Werribee Mansion; semi-private",
    "lat": -37.9,
    "lng": 144.6667
  },
  {
    "name": "Eastern Sward Golf Club",
    "suburb": "Bangholme",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "South-east; semi-private",
    "lat": -38.0,
    "lng": 145.1667
  },
  {
    "name": "Australasian Golf Club / Chelsea",
    "suburb": "Edithvale",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Semi-Private",
    "notes": "South-east coastal; semi-private",
    "lat": -38.05,
    "lng": 145.1333
  },
  {
    "name": "Bembridge Public Golf Course",
    "suburb": "Somerville",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "Peninsula fringe; semi-private",
    "lat": -38.2167,
    "lng": 145.1667
  },
  {
    "name": "Keysborough Golf Club",
    "suburb": "Keysborough",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$48",
    "access": "Semi-Private",
    "notes": "Sandbelt-adjacent; semi-private",
    "lat": -38.0,
    "lng": 145.1667
  },
  {
    "name": "Spring Valley Golf Club",
    "suburb": "Clayton South",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$110\u2013$130",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top-ranked Sandbelt; visitors Mon/Tue/Thu/Fri/Sun; strict dress code",
    "lat": -37.95,
    "lng": 145.1167
  },
  {
    "name": "Frankston Golf Club",
    "suburb": "Frankston",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$60\u2013$90",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top-50 ranked; members' club; visitors most weekdays",
    "lat": -38.15,
    "lng": 145.1167
  },
  {
    "name": "Capital Golf Club",
    "suburb": "Heatherton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$75",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Sandbelt-adjacent; members' club welcoming visitors",
    "lat": -37.9667,
    "lng": 145.0833
  },
  {
    "name": "Kingston Links Golf Club",
    "suburb": "Rowville",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Members' club; visitor tee times available",
    "lat": -37.9333,
    "lng": 145.2167
  },
  {
    "name": "Kingswood Golf Club",
    "suburb": "Dingley Village",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$40\u2013$60",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Sandbelt-adjacent; members' club; visitors most days",
    "lat": -37.9833,
    "lng": 145.1167
  },
  {
    "name": "Commonwealth Golf Club",
    "suburb": "Oakleigh South",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "$120\u2013$180",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "World-class Sandbelt; private but accepts visitors via reciprocal/tour",
    "lat": -37.9333,
    "lng": 145.0833
  },
  {
    "name": "Huntingdale Golf Club",
    "suburb": "Oakleigh South",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$120\u2013$180",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Sandbelt classic; private; limited visitor access",
    "lat": -37.9333,
    "lng": 145.0833
  },
  {
    "name": "Metropolitan Golf Club",
    "suburb": "South Oakleigh",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$130\u2013$200",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Sandbelt elite; visitors Mon, Wed/Thu mornings, Fri",
    "lat": -37.9333,
    "lng": 145.1
  },
  {
    "name": "Yarra Yarra Golf Club",
    "suburb": "Bentleigh East",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$130\u2013$200",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Alex Russell Sandbelt classic; limited visitor access",
    "lat": -37.9333,
    "lng": 145.05
  },
  {
    "name": "Victoria Golf Club",
    "suburb": "Cheltenham",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$130\u2013$200",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "World top-20; private; visitors via reciprocal/booking",
    "lat": -37.95,
    "lng": 145.05
  },
  {
    "name": "Kingston Heath Golf Club",
    "suburb": "Cheltenham",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$150\u2013$220",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "2028 Presidents Cup host; private; very limited visitor access",
    "lat": -37.95,
    "lng": 145.05
  },
  {
    "name": "Royal Melbourne GC \u2013 West Course",
    "suburb": "Black Rock",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$200\u2013$350",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "#1 in Australia; private; visitor access via tour operators or reciprocal",
    "lat": -37.9667,
    "lng": 145.0167
  },
  {
    "name": "Royal Melbourne GC \u2013 East Course",
    "suburb": "Black Rock",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$150\u2013$250",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Private; visitor access via reciprocal or tour operators",
    "lat": -37.9667,
    "lng": 145.0167
  },
  {
    "name": "Woodlands Golf Club",
    "suburb": "Mordialloc",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$130\u2013$180",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Underrated Sandbelt gem; green fee available 'upon application'",
    "lat": -38.0,
    "lng": 145.0833
  },
  {
    "name": "Heidelberg Golf Club",
    "suburb": "Lower Plenty",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$75",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Private; visitors welcome most weekdays",
    "lat": -37.7333,
    "lng": 145.1167
  },
  {
    "name": "Box Hill Golf Club",
    "suburb": "Box Hill",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$45\u2013$65",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Members' club; visitors welcome most days",
    "lat": -37.8167,
    "lng": 145.1167
  },
  {
    "name": "Green Acres Golf Club",
    "suburb": "Kew East",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$75",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Members' club; visitors welcome",
    "lat": -37.8,
    "lng": 145.05
  },
  {
    "name": "Kew Golf Club",
    "suburb": "Kew East",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$45\u2013$65",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Inner-east; members' club; visitors welcome most days",
    "lat": -37.8,
    "lng": 145.05
  },
  {
    "name": "Beaconhills Country Club",
    "suburb": "Beaconsfield Upper",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "South-east; member club; visitors welcome",
    "lat": -38.05,
    "lng": 145.4167
  },
  {
    "name": "Kilmore Golf Club",
    "suburb": "Kilmore",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Regional; members' club; visitors welcome",
    "lat": -37.3,
    "lng": 144.95
  },
  {
    "name": "Hidden Valley Golf & Country Club",
    "suburb": "Wallan",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "North corridor; visitors welcome",
    "lat": -37.4167,
    "lng": 144.9833
  },
  {
    "name": "Gisborne Golf Club",
    "suburb": "Gisborne",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Macedon Ranges; visitors welcome",
    "lat": -37.4833,
    "lng": 144.5833
  },
  {
    "name": "Long Island Country Club",
    "suburb": "Frankston South",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$80",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Sandbelt gateway; 'hidden gem'; visitors welcome",
    "lat": -38.1833,
    "lng": 145.1333
  },
  {
    "name": "Centenary Park Golf Course",
    "suburb": "Frankston",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$45",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Municipal/public-access course near Frankston",
    "lat": -38.15,
    "lng": 145.1167
  },
  {
    "name": "Riversdale Golf Club",
    "suburb": "Oakleigh South",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$60\u2013$90",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top-100 ranked; private Sandbelt; visitors via arrangement",
    "lat": -37.9333,
    "lng": 145.0833
  },
  {
    "name": "The Eastern Golf Club \u2013 South Course",
    "suburb": "Yering",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "N/A \u2013 Private",
    "access": "Private",
    "notes": "Greg Norman design; top-ranked; private members only",
    "lat": -37.7167,
    "lng": 145.3833
  },
  {
    "name": "The Eastern Golf Club \u2013 North Course",
    "suburb": "Yering",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "N/A \u2013 Private",
    "access": "Private",
    "notes": "Greg Norman design; private members only",
    "lat": -37.7167,
    "lng": 145.3833
  },
  {
    "name": "Rosanna Golf Club",
    "suburb": "Lower Plenty",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "N/A \u2013 Private",
    "access": "Private",
    "notes": "Private members' club",
    "lat": -37.7333,
    "lng": 145.1167
  },
  {
    "name": "Heritage Golf & CC \u2013 Henley Course",
    "suburb": "Chirnside Park",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "N/A \u2013 Private",
    "access": "Private",
    "notes": "Top-100 ranked; private; members & guests only",
    "lat": -37.75,
    "lng": 145.3333
  },
  {
    "name": "Heritage Golf & CC \u2013 St John Course",
    "suburb": "Chirnside Park",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "N/A \u2013 Private",
    "access": "Private",
    "notes": "Top-100 ranked; private; members & guests only",
    "lat": -37.75,
    "lng": 145.3333
  },
  {
    "name": "Warburton Golf Club",
    "suburb": "Warburton",
    "holes": 18,
    "par": "69",
    "fee9": "$21\u2013$28",
    "fee18": "$35\u2013$48",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Scenic mountain course; 90 min from CBD; visitors welcome 7 days; no bunkers; club hire available",
    "lat": -37.75,
    "lng": 145.6833
  },
  {
    "name": "Yering Meadows Golf Club",
    "suburb": "Yering",
    "holes": 27,
    "par": "108",
    "fee9": "$35\u2013$50",
    "fee18": "$55\u2013$75",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "27 holes; formerly Croydon GC; Yarra Valley views; visitors welcome",
    "lat": -37.7167,
    "lng": 145.3833
  },
  {
    "name": "RACV Healesville Country Club",
    "suburb": "Healesville",
    "holes": 18,
    "par": "68",
    "fee9": "N/A",
    "fee18": "$45\u2013$70",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Michael Clayton design; Top-100; resort members & public welcome",
    "lat": -37.65,
    "lng": 145.5167
  },
  {
    "name": "Emerald Golf & Country Resort",
    "suburb": "Emerald",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Resort / Public",
    "notes": "Dandenongs resort; public green fees",
    "lat": -37.9333,
    "lng": 145.4333
  },
  {
    "name": "Eildon Golf Club",
    "suburb": "Eildon",
    "holes": 9,
    "par": "34",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "High country 9-hole scenic semi-private",
    "lat": -37.2333,
    "lng": 145.9
  },
  {
    "name": "Alexandra Golf Club",
    "suburb": "Alexandra",
    "holes": 9,
    "par": "35",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Murrindindi 9-hole semi-private",
    "lat": -37.19,
    "lng": 145.7167
  },
  {
    "name": "Cathedral Golf Club",
    "suburb": "Thornton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$250\u2013$400",
    "access": "Private",
    "notes": "Ultra-exclusive Greg Norman design; invitation/member only",
    "lat": -37.3,
    "lng": 145.8333
  },
  {
    "name": "Marysville Golf Course",
    "suburb": "Marysville",
    "holes": 9,
    "par": "34",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Small mountain town public 9-hole",
    "lat": -37.5167,
    "lng": 145.75
  },
  {
    "name": "Eagle Ridge Golf Course",
    "suburb": "Boneo",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$65\u2013$90",
    "access": "Public",
    "notes": "Public 18-hole near Rye; resort-style facilities",
    "lat": -38.4167,
    "lng": 144.8833
  },
  {
    "name": "Moonah Links \u2013 Open Course",
    "suburb": "Fingal",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$80\u2013$130",
    "access": "Resort / Public",
    "notes": "Public-access resort; hosted 2003 & 2005 Australian Open",
    "lat": -38.45,
    "lng": 144.8833
  },
  {
    "name": "Moonah Links \u2013 Legends Course",
    "suburb": "Fingal",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$100\u2013$175",
    "access": "Resort / Public",
    "notes": "Public-access resort; Top-100 ranked",
    "lat": -38.45,
    "lng": 144.8833
  },
  {
    "name": "St Andrews Beach Golf Course",
    "suburb": "Fingal",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$90\u2013$185",
    "access": "Resort / Public",
    "notes": "Tom Doak / Mike Clayton links; public resort; Top-100",
    "lat": -38.45,
    "lng": 144.8833
  },
  {
    "name": "The Dunes Golf Links",
    "suburb": "Rye",
    "holes": 27,
    "par": "108",
    "fee9": "$45\u2013$70",
    "fee18": "$75\u2013$110",
    "access": "Public",
    "notes": "27 holes; 18+9 layout; public access links; Tony Cashmore design",
    "lat": -38.3667,
    "lng": 144.8333
  },
  {
    "name": "RACV Cape Schanck Resort",
    "suburb": "Cape Schanck",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$80\u2013$145",
    "access": "Resort / Public",
    "notes": "Resort course at Peninsula tip; public green fees",
    "lat": -38.5,
    "lng": 144.9
  },
  {
    "name": "Sanctuary Lakes Golf Club",
    "suburb": "Point Cook",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$80",
    "access": "Resort / Public",
    "notes": "Resort/residential; public green fees available",
    "lat": -37.9167,
    "lng": 144.75
  },
  {
    "name": "Bay Views Golf Course",
    "suburb": "Rosebud",
    "holes": 9,
    "par": "36",
    "fee9": "$20\u2013$28",
    "fee18": "N/A",
    "access": "Public",
    "notes": "9-hole public on the Peninsula",
    "lat": -38.35,
    "lng": 144.9
  },
  {
    "name": "Devilbend Golf Club",
    "suburb": "Moorooduc",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Semi-Private",
    "notes": "Gateway to Peninsula; semi-private; visitors welcome",
    "lat": -38.2833,
    "lng": 145.2
  },
  {
    "name": "Mornington Golf Club",
    "suburb": "Mornington",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$50\u2013$75",
    "access": "Semi-Private",
    "notes": "Top-100 ranked; open visitor tee times",
    "lat": -38.2167,
    "lng": 145.0333
  },
  {
    "name": "Rosebud Country Club \u2013 North",
    "suburb": "Rosebud",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$45\u2013$65",
    "access": "Semi-Private",
    "notes": "Peninsula; 36-hole complex; semi-private",
    "lat": -38.35,
    "lng": 144.9
  },
  {
    "name": "Rosebud Country Club \u2013 South",
    "suburb": "Rosebud",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$45\u2013$65",
    "access": "Semi-Private",
    "notes": "Peninsula; 36-hole complex; semi-private",
    "lat": -38.35,
    "lng": 144.9
  },
  {
    "name": "Sorrento Golf Club",
    "suburb": "Sorrento",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$75",
    "access": "Semi-Private",
    "notes": "Cliff-top views; members' club; visitors welcome",
    "lat": -38.3333,
    "lng": 144.75
  },
  {
    "name": "Portsea Golf Club",
    "suburb": "Portsea",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "$75\u2013$120",
    "access": "Semi-Private",
    "notes": "Links-style; members' club; visitors welcome",
    "lat": -38.3333,
    "lng": 144.7167
  },
  {
    "name": "Flinders Golf Club",
    "suburb": "Flinders",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$70",
    "access": "Semi-Private",
    "notes": "Coastal; members' club; visitors welcome",
    "lat": -38.4833,
    "lng": 145.0167
  },
  {
    "name": "Amstel Golf Club \u2013 Ranfurlie",
    "suburb": "Cranbourne",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Semi-Private",
    "notes": "Semi-private; Ranfurlie layout; public tee times available",
    "lat": -38.1167,
    "lng": 145.2833
  },
  {
    "name": "Peninsula Kingswood CC \u2013 North",
    "suburb": "Frankston South",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$100\u2013$175",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top-5 in Australia; private; limited visitor access",
    "lat": -38.1833,
    "lng": 145.1333
  },
  {
    "name": "Peninsula Kingswood CC \u2013 South",
    "suburb": "Frankston South",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$80\u2013$140",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Alongside North course; private; visitors by arrangement",
    "lat": -38.1833,
    "lng": 145.1333
  },
  {
    "name": "The National GC \u2013 Moonah",
    "suburb": "Frankston",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$150\u2013$250",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Private; interstate/overseas visitors can book directly online",
    "lat": -38.15,
    "lng": 145.1167
  },
  {
    "name": "The National GC \u2013 Gunnamatta",
    "suburb": "Frankston",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$150\u2013$250",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Private; interstate/overseas visitors can book directly online",
    "lat": -38.15,
    "lng": 145.1167
  },
  {
    "name": "The National GC \u2013 Old Course",
    "suburb": "Frankston",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$100\u2013$180",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Private; interstate/overseas visitors can book directly online",
    "lat": -38.15,
    "lng": 145.1167
  },
  {
    "name": "Lonsdale Links Golf Club",
    "suburb": "Queenscliff",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$75\u2013$120",
    "access": "Public",
    "notes": "Top-ranked links; public pay-and-play",
    "lat": -38.2667,
    "lng": 144.6667
  },
  {
    "name": "Curlewis Golf Club",
    "suburb": "Curlewis",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$60\u2013$90",
    "access": "Public",
    "notes": "Top-100; public access; accommodation on site",
    "lat": -38.1667,
    "lng": 144.4333
  },
  {
    "name": "Thirteenth Beach GLC \u2013 Beach Course",
    "suburb": "Barwon Heads",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$75\u2013$110",
    "access": "Resort / Public",
    "notes": "Championship links; resort; 3 courses on site",
    "lat": -38.2667,
    "lng": 144.5
  },
  {
    "name": "Thirteenth Beach GLC \u2013 Creek Course",
    "suburb": "Barwon Heads",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$65\u2013$95",
    "access": "Resort / Public",
    "notes": "Second layout; resort public access",
    "lat": -38.2667,
    "lng": 144.5
  },
  {
    "name": "Thirteenth Beach GLC \u2013 Short Course",
    "suburb": "Barwon Heads",
    "holes": 9,
    "par": "27",
    "fee9": "$25\u2013$35",
    "fee18": "N/A",
    "access": "Resort / Public",
    "notes": "9-hole short course; resort; all abilities",
    "lat": -38.2667,
    "lng": 144.5
  },
  {
    "name": "Sandy Links Golf Club",
    "suburb": "Waurn Ponds",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$80",
    "access": "Public",
    "notes": "Geelong-area public links; free golf U16 with paying adult",
    "lat": -38.2167,
    "lng": 144.3
  },
  {
    "name": "Portarlington Golf Club",
    "suburb": "Portarlington",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Semi-Private",
    "notes": "Bellarine Peninsula semi-private",
    "lat": -38.1167,
    "lng": 144.65
  },
  {
    "name": "Clifton Springs Golf Club",
    "suburb": "Clifton Springs",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$50",
    "access": "Semi-Private",
    "notes": "Bellarine; semi-private; council-owned course",
    "lat": -38.15,
    "lng": 144.5667
  },
  {
    "name": "Bellarine Lakes Golf Club",
    "suburb": "Moolap",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$48",
    "access": "Semi-Private",
    "notes": "Geelong-adjacent semi-private",
    "lat": -38.1667,
    "lng": 144.4167
  },
  {
    "name": "Balyang Par Three Golf Course",
    "suburb": "Newtown (Geelong)",
    "holes": 9,
    "par": "27",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Par-3 public course in Geelong",
    "lat": -38.15,
    "lng": 144.3333
  },
  {
    "name": "Geelong Golf Club",
    "suburb": "Geelong",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Main Geelong course; members' club; visitors welcome",
    "lat": -38.15,
    "lng": 144.35
  },
  {
    "name": "East Geelong Golf Club",
    "suburb": "East Geelong",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Semi-Private",
    "notes": "Semi-private Geelong",
    "lat": -38.15,
    "lng": 144.3833
  },
  {
    "name": "Barwon Valley Golf Club",
    "suburb": "Belmont",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Semi-Private",
    "notes": "Geelong suburban semi-private",
    "lat": -38.1833,
    "lng": 144.35
  },
  {
    "name": "Barwon Heads Golf Club",
    "suburb": "Barwon Heads",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "$60\u2013$90",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top-ranked; private members' club; visitors welcome most days",
    "lat": -38.2667,
    "lng": 144.5
  },
  {
    "name": "Anglesea Golf Club",
    "suburb": "Anglesea",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Semi-Private",
    "notes": "Famous for resident kangaroos; semi-private; visitors welcome",
    "lat": -38.4,
    "lng": 144.1833
  },
  {
    "name": "Apollo Bay Golf Club",
    "suburb": "Apollo Bay",
    "holes": 9,
    "par": "34",
    "fee9": "$20\u2013$28",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole; Great Ocean Road; semi-private",
    "lat": -38.75,
    "lng": 143.6667
  },
  {
    "name": "Colac Golf Club",
    "suburb": "Elliminyt",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "South-west regional semi-private",
    "lat": -38.3667,
    "lng": 143.5833
  },
  {
    "name": "Camperdown Golf Club",
    "suburb": "Camperdown",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$25\u2013$35",
    "access": "Semi-Private",
    "notes": "Volcanic lakes region; semi-private",
    "lat": -38.6667,
    "lng": 143.15
  },
  {
    "name": "Inverleigh Golf Club",
    "suburb": "Inverleigh",
    "holes": 9,
    "par": "35",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Rural 9-hole semi-private",
    "lat": -38.1,
    "lng": 144.05
  },
  {
    "name": "Port Fairy Golf Club",
    "suburb": "Port Fairy",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$40\u2013$65",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top-50 ranked links; members' club; visitors warmly welcomed",
    "lat": -38.3833,
    "lng": 142.2333
  },
  {
    "name": "Warrnambool Golf Club",
    "suburb": "Warrnambool",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Regional hub; members' club; visitors welcome",
    "lat": -38.3833,
    "lng": 142.4833
  },
  {
    "name": "Hamilton Golf Club",
    "suburb": "Hamilton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Semi-Private",
    "notes": "Regional south-west; semi-private",
    "lat": -37.7333,
    "lng": 142.0167
  },
  {
    "name": "Casterton Golf Club",
    "suburb": "Casterton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$20\u2013$30",
    "access": "Semi-Private",
    "notes": "Rural semi-private",
    "lat": -37.5833,
    "lng": 141.4
  },
  {
    "name": "Heywood Golf Club",
    "suburb": "Heywood",
    "holes": 9,
    "par": "35",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole rural semi-private",
    "lat": -38.1333,
    "lng": 141.6333
  },
  {
    "name": "Coleraine Golf Club",
    "suburb": "Coleraine",
    "holes": 9,
    "par": "34",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Rural 9-hole semi-private",
    "lat": -37.5833,
    "lng": 141.6833
  },
  {
    "name": "East Framlingham Golf Club",
    "suburb": "Framlingham",
    "holes": 9,
    "par": "34",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Rural 9-hole semi-private",
    "lat": -38.2167,
    "lng": 142.6
  },
  {
    "name": "Portland Golf Club",
    "suburb": "Portland",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$25\u2013$35",
    "access": "Semi-Private",
    "notes": "Far south-west regional semi-private",
    "lat": -38.35,
    "lng": 141.6
  },
  {
    "name": "Dartmoor Golf Club",
    "suburb": "Dartmoor",
    "holes": 9,
    "par": "34",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small rural 9-hole",
    "lat": -37.9167,
    "lng": 141.2833
  },
  {
    "name": "Ballarat Golf Club",
    "suburb": "Alfredton",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "$35\u2013$55",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top-100 regional; visitors welcome 7 days",
    "lat": -37.55,
    "lng": 143.8
  },
  {
    "name": "Buninyong Golf Club",
    "suburb": "Buninyong",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Near Ballarat; members' club; visitors welcome",
    "lat": -37.65,
    "lng": 143.8833
  },
  {
    "name": "Chalambar Golf Club",
    "suburb": "Ararat",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "One of regional VIC's best; visitors welcome",
    "lat": -37.2833,
    "lng": 142.9167
  },
  {
    "name": "Aradale Golf Club",
    "suburb": "Ararat",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$22\u2013$32",
    "access": "Semi-Private",
    "notes": "Ararat; semi-private",
    "lat": -37.2833,
    "lng": 142.9167
  },
  {
    "name": "Hepburn Springs Golf Club",
    "suburb": "Hepburn Springs",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Spa country; visitors welcome",
    "lat": -37.3167,
    "lng": 144.1333
  },
  {
    "name": "Beaufort Golf Club",
    "suburb": "Beaufort",
    "holes": 9,
    "par": "33",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole rural semi-private",
    "lat": -37.4333,
    "lng": 143.3833
  },
  {
    "name": "Creswick Forest Resort Golf",
    "suburb": "Creswick",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Resort / Public",
    "notes": "Resort public course near Ballarat",
    "lat": -37.4333,
    "lng": 143.8833
  },
  {
    "name": "Halls Gap Golf Club",
    "suburb": "Halls Gap",
    "holes": 9,
    "par": "36",
    "fee9": "$20\u2013$28",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Grampians setting; 9-hole semi-private",
    "lat": -37.1333,
    "lng": 142.5167
  },
  {
    "name": "Horsham Golf Club",
    "suburb": "Horsham",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Regional north-west; visitors welcome",
    "lat": -36.7167,
    "lng": 142.2
  },
  {
    "name": "Dimboola Golf Club",
    "suburb": "Dimboola",
    "holes": 9,
    "par": "33",
    "fee9": "$15\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole rural semi-private",
    "lat": -36.45,
    "lng": 142.0167
  },
  {
    "name": "Donald Golf Club",
    "suburb": "Donald",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$20\u2013$28",
    "access": "Semi-Private",
    "notes": "Rural north-west semi-private",
    "lat": -36.3667,
    "lng": 142.9833
  },
  {
    "name": "Grampians Golf Club",
    "suburb": "Dunkeld",
    "holes": 9,
    "par": "35",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Grampians backdrop; 9-hole semi-private",
    "lat": -37.65,
    "lng": 142.3333
  },
  {
    "name": "Grange Golf Club",
    "suburb": "Stawell",
    "holes": 9,
    "par": "34",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Stawell 9-hole rural semi-private",
    "lat": -37.05,
    "lng": 142.7667
  },
  {
    "name": "Glenorchy Golf Club",
    "suburb": "Glenorchy",
    "holes": 9,
    "par": "35",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Rural 9-hole semi-private",
    "lat": -36.9167,
    "lng": 143.9
  },
  {
    "name": "Bendigo Golf Club",
    "suburb": "Epsom",
    "holes": 27,
    "par": "108",
    "fee9": "$30\u2013$45",
    "fee18": "$42\u2013$60",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "27 holes; major regional club; visitors welcome",
    "lat": -36.7167,
    "lng": 144.35
  },
  {
    "name": "Eaglehawk Golf Club",
    "suburb": "Eaglehawk",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Bendigo area; members' club; visitors welcome",
    "lat": -36.7167,
    "lng": 144.2333
  },
  {
    "name": "Neangar Park Golf Club",
    "suburb": "Eaglehawk",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Bendigo-area; visitors welcome; popular regional course",
    "lat": -36.7167,
    "lng": 144.2333
  },
  {
    "name": "Axedale Golf Club",
    "suburb": "Axedale",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$22\u2013$32",
    "access": "Semi-Private",
    "notes": "Rural Bendigo-area; semi-private",
    "lat": -36.75,
    "lng": 144.5333
  },
  {
    "name": "Castlemaine Golf Club",
    "suburb": "Castlemaine",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$25\u2013$35",
    "access": "Semi-Private",
    "notes": "Goldfields town; semi-private",
    "lat": -37.0667,
    "lng": 144.2167
  },
  {
    "name": "Kyneton Golf Club",
    "suburb": "Kyneton",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$25\u2013$35",
    "access": "Semi-Private",
    "notes": "Central Victoria; semi-private",
    "lat": -37.25,
    "lng": 144.45
  },
  {
    "name": "Dunolly Golf Club",
    "suburb": "Dunolly",
    "holes": 9,
    "par": "33",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Goldfields 9-hole semi-private",
    "lat": -36.85,
    "lng": 143.7333
  },
  {
    "name": "Avoca Golf Club",
    "suburb": "Avoca",
    "holes": 9,
    "par": "34",
    "fee9": "$14\u2013$18",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Small rural 9-hole public course",
    "lat": -37.0833,
    "lng": 143.4667
  },
  {
    "name": "Inglewood Golf Club",
    "suburb": "Inglewood",
    "holes": 9,
    "par": "34",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small rural 9-hole semi-private",
    "lat": -36.5833,
    "lng": 143.8667
  },
  {
    "name": "Clunes Golf Club",
    "suburb": "Clunes",
    "holes": 9,
    "par": "33",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Gold rush town 9-hole semi-private",
    "lat": -37.2833,
    "lng": 143.7833
  },
  {
    "name": "Maryborough Golf Club",
    "suburb": "Maryborough",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$22\u2013$32",
    "access": "Semi-Private",
    "notes": "Goldfields semi-private",
    "lat": -37.05,
    "lng": 143.7333
  },
  {
    "name": "Bridgewater-on-Loddon Golf Club",
    "suburb": "Bridgewater",
    "holes": 9,
    "par": "35",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Rural 9-hole semi-private",
    "lat": -36.6,
    "lng": 143.95
  },
  {
    "name": "Charlton Golf Club",
    "suburb": "Charlton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$18\u2013$28",
    "access": "Semi-Private",
    "notes": "Regional semi-private",
    "lat": -36.2667,
    "lng": 143.35
  },
  {
    "name": "Boort Golf Club",
    "suburb": "Boort",
    "holes": 9,
    "par": "35",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small rural 9-hole",
    "lat": -36.1167,
    "lng": 143.7167
  },
  {
    "name": "Broadford Golf Club",
    "suburb": "Broadford",
    "holes": 9,
    "par": "34",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small town 9-hole semi-private",
    "lat": -37.2,
    "lng": 145.05
  },
  {
    "name": "Shepparton Golf Club",
    "suburb": "Shepparton",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top regional course; visitors welcome 7 days",
    "lat": -36.3833,
    "lng": 145.4
  },
  {
    "name": "Cobram Barooga Golf Club",
    "suburb": "Cobram",
    "holes": 36,
    "par": "144",
    "fee9": "$30\u2013$45",
    "fee18": "$45\u2013$65",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "36 holes; top Murray complex; visitors welcome",
    "lat": -35.9167,
    "lng": 145.65
  },
  {
    "name": "Yarrawonga-Mulwala GC Resort",
    "suburb": "Yarrawonga",
    "holes": 36,
    "par": "144",
    "fee9": "$30\u2013$45",
    "fee18": "$55\u2013$80",
    "access": "Resort / Public",
    "notes": "45 holes; Australia's largest public golf complex",
    "lat": -36.0167,
    "lng": 146.0
  },
  {
    "name": "Black Bull Golf Club Yarrawonga",
    "suburb": "Yarrawonga",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$50\u2013$80",
    "access": "Resort / Public",
    "notes": "Top-100 ranked; resort-style public",
    "lat": -36.0167,
    "lng": 146.0
  },
  {
    "name": "Echuca Back Nine Golf Course",
    "suburb": "Echuca",
    "holes": 9,
    "par": "36",
    "fee9": "$20\u2013$28",
    "fee18": "N/A",
    "access": "Public",
    "notes": "Public 9-hole Echuca",
    "lat": -36.1333,
    "lng": 144.75
  },
  {
    "name": "Kyabram Parkland Golf Club",
    "suburb": "Kyabram",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$25\u2013$35",
    "access": "Semi-Private",
    "notes": "Rural Victoria semi-private",
    "lat": -36.3167,
    "lng": 145.05
  },
  {
    "name": "Cohuna Golf Club",
    "suburb": "Cohuna",
    "holes": 9,
    "par": "34",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole Murray region semi-private",
    "lat": -35.8167,
    "lng": 144.2167
  },
  {
    "name": "Kerang Golf Club",
    "suburb": "Kerang",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$22\u2013$32",
    "access": "Semi-Private",
    "notes": "North-west rural semi-private",
    "lat": -35.7333,
    "lng": 143.9167
  },
  {
    "name": "Campaspe Golf Club",
    "suburb": "Rochester",
    "holes": 9,
    "par": "35",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole rural semi-private",
    "lat": -36.3667,
    "lng": 144.7
  },
  {
    "name": "Hill Top Golf & Country Club",
    "suburb": "Tatura",
    "holes": 9,
    "par": "36",
    "fee9": "$18\u2013$25",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole semi-private",
    "lat": -36.4333,
    "lng": 145.2333
  },
  {
    "name": "Numurkah Golf Club",
    "suburb": "Numurkah",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$22\u2013$32",
    "access": "Semi-Private",
    "notes": "Murray region semi-private",
    "lat": -36.0833,
    "lng": 145.4333
  },
  {
    "name": "Tongala Golf Club",
    "suburb": "Tongala",
    "holes": 9,
    "par": "35",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small rural 9-hole",
    "lat": -36.25,
    "lng": 144.9667
  },
  {
    "name": "Wangaratta Golf Club",
    "suburb": "Wangaratta",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "North-east regional; visitors welcome",
    "lat": -36.3583,
    "lng": 146.3167
  },
  {
    "name": "Wodonga Golf Club",
    "suburb": "Wodonga",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Border city; visitors welcome",
    "lat": -36.1167,
    "lng": 146.8833
  },
  {
    "name": "Benalla Golf Club",
    "suburb": "Benalla",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "North-east; visitors welcome",
    "lat": -36.55,
    "lng": 145.9833
  },
  {
    "name": "Bright Country Golf Club",
    "suburb": "Bright",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Alpine valley; visitors welcome; great scenery",
    "lat": -36.7333,
    "lng": 146.95
  },
  {
    "name": "Beechworth Golf Club",
    "suburb": "Beechworth",
    "holes": 9,
    "par": "34",
    "fee9": "$18\u2013$25",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Historic town 9-hole; semi-private",
    "lat": -36.3667,
    "lng": 146.6833
  },
  {
    "name": "Mount Beauty Golf Club",
    "suburb": "Mount Beauty",
    "holes": 9,
    "par": "35",
    "fee9": "$18\u2013$25",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Alpine 9-hole; mountain views",
    "lat": -36.7333,
    "lng": 147.1667
  },
  {
    "name": "Corryong Golf Club",
    "suburb": "Corryong",
    "holes": 9,
    "par": "34",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Upper Murray 9-hole semi-private",
    "lat": -36.2,
    "lng": 147.9
  },
  {
    "name": "Mansfield Golf Club",
    "suburb": "Mansfield",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Public",
    "notes": "High country; public; visitors welcome all week",
    "lat": -37.05,
    "lng": 146.0833
  },
  {
    "name": "Euroa Golf Club",
    "suburb": "Euroa",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$22\u2013$32",
    "access": "Semi-Private",
    "notes": "North-east Victoria semi-private",
    "lat": -36.75,
    "lng": 145.5667
  },
  {
    "name": "Seymour Golf Club",
    "suburb": "Seymour",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$22\u2013$32",
    "access": "Semi-Private",
    "notes": "Central Victoria semi-private",
    "lat": -37.0167,
    "lng": 145.1333
  },
  {
    "name": "Myrtleford Golf Club",
    "suburb": "Myrtleford",
    "holes": 9,
    "par": "35",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Alpine foothills 9-hole semi-private",
    "lat": -36.5667,
    "lng": 146.7333
  },
  {
    "name": "Jubilee Golf Club",
    "suburb": "Wangaratta",
    "holes": 9,
    "par": "35",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Rural 9-hole semi-private near Wangaratta",
    "lat": -36.3583,
    "lng": 146.3167
  },
  {
    "name": "Barnawartha Golf Club",
    "suburb": "Barnawartha",
    "holes": 9,
    "par": "34",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small border town 9-hole",
    "lat": -36.1,
    "lng": 146.95
  },
  {
    "name": "Chiltern Golf Club",
    "suburb": "Chiltern",
    "holes": 9,
    "par": "34",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Historic Chiltern; 9-hole semi-private",
    "lat": -36.15,
    "lng": 146.6
  },
  {
    "name": "Bairnsdale Golf Club",
    "suburb": "Eagle Point",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "East Gippsland; visitors welcome",
    "lat": -37.8833,
    "lng": 147.6833
  },
  {
    "name": "Lakes Entrance Golf Club",
    "suburb": "Lakes Entrance",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Scenic coastal; visitors welcome",
    "lat": -37.8833,
    "lng": 147.9833
  },
  {
    "name": "Leongatha Golf Club",
    "suburb": "Leongatha",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Top-regional Vern Morcom design; visitors welcome 7 days",
    "lat": -38.4833,
    "lng": 145.9333
  },
  {
    "name": "Drouin Golf and Country Club",
    "suburb": "Drouin",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "$30\u2013$45",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "West Gippsland; visitors welcome",
    "lat": -38.1333,
    "lng": 145.85
  },
  {
    "name": "Traralgon Golf Club",
    "suburb": "Traralgon",
    "holes": 18,
    "par": "73",
    "fee9": "N/A",
    "fee18": "$28\u2013$42",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Gippsland regional; visitors welcome",
    "lat": -38.1833,
    "lng": 146.5333
  },
  {
    "name": "Sale Golf Club",
    "suburb": "Sale",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "East Gippsland; visitors welcome",
    "lat": -38.1,
    "lng": 147.0667
  },
  {
    "name": "Morwell Golf Club",
    "suburb": "Morwell",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "Latrobe Valley; visitors welcome",
    "lat": -38.2333,
    "lng": 146.3833
  },
  {
    "name": "Warragul Golf Club",
    "suburb": "Warragul",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Members \u2013 Visitors Welcome",
    "notes": "West Gippsland; visitors welcome",
    "lat": -38.1667,
    "lng": 145.9333
  },
  {
    "name": "Mirboo North Golf Club",
    "suburb": "Mirboo North",
    "holes": 9,
    "par": "35",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "South Gippsland hills; semi-private",
    "lat": -38.3833,
    "lng": 146.1667
  },
  {
    "name": "Foster Golf Club",
    "suburb": "Foster",
    "holes": 9,
    "par": "34",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "South Gippsland 9-hole; semi-private",
    "lat": -38.65,
    "lng": 146.1833
  },
  {
    "name": "Garfield Golf Club",
    "suburb": "Garfield",
    "holes": 9,
    "par": "35",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "West Gippsland 9-hole semi-private",
    "lat": -38.0833,
    "lng": 145.9333
  },
  {
    "name": "Korumburra Golf Club",
    "suburb": "Korumburra",
    "holes": 9,
    "par": "35",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "South Gippsland 9-hole semi-private",
    "lat": -38.4333,
    "lng": 145.8167
  },
  {
    "name": "Heyfield Golf Club",
    "suburb": "Heyfield",
    "holes": 9,
    "par": "35",
    "fee9": "$15\u2013$22",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "9-hole Gippsland semi-private",
    "lat": -37.9833,
    "lng": 146.7833
  },
  {
    "name": "Buchan Valley Golf Club",
    "suburb": "Buchan",
    "holes": 9,
    "par": "33",
    "fee9": "$12\u2013$18",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Remote East Gippsland 9-hole",
    "lat": -37.5,
    "lng": 148.1667
  },
  {
    "name": "Churchill & Monash Golf Club",
    "suburb": "Churchill",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Semi-Private",
    "notes": "Latrobe Valley semi-private",
    "lat": -38.3167,
    "lng": 146.4167
  },
  {
    "name": "Moe Golf Club",
    "suburb": "Moe",
    "holes": 18,
    "par": "70",
    "fee9": "N/A",
    "fee18": "$25\u2013$35",
    "access": "Semi-Private",
    "notes": "Latrobe Valley; semi-private",
    "lat": -38.1667,
    "lng": 146.2667
  },
  {
    "name": "Newry Golf Club",
    "suburb": "Newry",
    "holes": 9,
    "par": "35",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Remote Gippsland 9-hole",
    "lat": -37.9167,
    "lng": 146.9
  },
  {
    "name": "Pakenham Golf Club",
    "suburb": "Pakenham",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$28\u2013$40",
    "access": "Semi-Private",
    "notes": "South-east growth corridor semi-private",
    "lat": -38.0667,
    "lng": 145.4833
  },
  {
    "name": "Mildura Golf Resort",
    "suburb": "Mildura",
    "holes": 18,
    "par": "71",
    "fee9": "N/A",
    "fee18": "$30\u2013$50",
    "access": "Resort / Public",
    "notes": "Murray resort; public green fees",
    "lat": -34.2333,
    "lng": 142.15
  },
  {
    "name": "Riverside Golf Club Mildura",
    "suburb": "Mildura",
    "holes": 18,
    "par": "72",
    "fee9": "N/A",
    "fee18": "$25\u2013$38",
    "access": "Semi-Private",
    "notes": "Murray River views; semi-private",
    "lat": -34.2333,
    "lng": 142.15
  },
  {
    "name": "Red Cliffs Golf Club",
    "suburb": "Red Cliffs",
    "holes": 9,
    "par": "34",
    "fee9": "$14\u2013$20",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small town 9-hole semi-private",
    "lat": -34.3,
    "lng": 142.1833
  },
  {
    "name": "Hopetoun Golf Club",
    "suburb": "Hopetoun",
    "holes": 9,
    "par": "34",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Far north-west rural 9-hole",
    "lat": -35.7167,
    "lng": 142.35
  },
  {
    "name": "Jeparit Golf Club",
    "suburb": "Jeparit",
    "holes": 9,
    "par": "34",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Remote rural 9-hole",
    "lat": -35.7,
    "lng": 142.0
  },
  {
    "name": "Kaniva Golf Club",
    "suburb": "Kaniva",
    "holes": 9,
    "par": "33",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Far west rural 9-hole",
    "lat": -36.3833,
    "lng": 141.2333
  },
  {
    "name": "Nhill Golf Club",
    "suburb": "Nhill",
    "holes": 9,
    "par": "35",
    "fee9": "$10\u2013$15",
    "fee18": "N/A",
    "access": "Semi-Private",
    "notes": "Small Wimmera town 9-hole",
    "lat": -36.3333,
    "lng": 141.65
  }
];
